name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital

  pipelines:
  - pipeline: build_pipeline
    source: "Reasonable-Adjustments-Build"
    trigger:
      branches:
        include:
          - refs/tags/v*

pool:
  name: 'AWS-ECS'

variables:
  - template: project.yml

extends:
  template: azure/common/apigee-deployment.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    service_base_path: ${{ variables.service_base_path }}
    prod_producer_approval: true
    prod_requires_approval: true
    enable_monitoring: true
    enable_status_monitoring: true
    apigee_deployments:
      - environment: internal-dev
        post_deploy:
            - template: templates/tests.yml
              parameters:
                  service_name: ${{ variables.service_name }}
      - environment: internal-qa
      - environment: internal-qa-sandbox
        proxy_path: sandbox
      - environment: int
        post_deploy:
            - template: templates/tests.yml
              parameters:
                  service_name: ${{ variables.service_name }}
        depends_on:
            - internal_qa
            - internal_qa_sandbox
      - environment: sandbox
        proxy_path: sandbox
        post_deploy:
            - template: templates/tests.yml
              parameters:
                  service_name: ${{ variables.service_name }}
        depends_on:
            - internal_qa
            - internal_qa_sandbox
      - environment: prod
        proxy_path: live
        depends_on:              # which environments to depend on before deploying
            - int
            - sandbox
        post_deploy:
            - template: templates/tests.yml
              parameters:
                  environment: 'prod'
                  service_name: ${{ variables.service_name }}
        