name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital

  pipelines:
  - pipeline: build_pipeline
    source: "Reasonable-Adjustments-Build"
    trigger:
      branches:
        include:
          - refs/tags/v*

pool:
  name: 'AWS-ECS'

variables:
  - template: project.yml

extends:
  template: azure/common/apigee-deployment.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    service_base_path: ${{ variables.service_base_path }}
    product_display_name: ${{ variables.product_display_name }}
    product_description: ${{ variables.product_description }}
    spec_file: ${{ variables.spec_file }}
    enable_monitoring: true
    secret_ids:
        - ptl/reasonable-adjustments/internal-dev/test_app/client_secret
        - ptl/app-credentials/internal-dev/INTERNAL_TESTING_WITHOUT_ASID_KEY
        - ptl/app-credentials/internal-dev/INTERNAL_TESTING_WITHOUT_ASID_SECRET
        - ptl/monitoring/status-endpoint-api-key
    config_ids:
        - /ptl/reasonable-adjustments/internal-dev/test_app/client_key
        - /ptl/azure-devops/env-int/test-app/ra-testing/RA_INT_CLIENT_ID
        - /ptl/azure-devops/env-int/test-app/ra-testing/RA_INT_CLIENT_SECRET
        - /ptl/app-credentials/internal-dev/INTERNAL_TESTING_WITHOUT_ODS_KEY
        - /ptl/app-credentials/internal-dev/INTERNAL_TESTING_WITHOUT_ODS_SECRET
    apigee_deployments:
      - environment: internal-dev
        make_spec_visible: true
        post_deploy:
            - template: templates/tests.yml
              parameters:
                  service_name: ${{ variables.service_name }}
      - environment: internal-qa
        make_spec_visible: true
      - environment: internal-qa-sandbox
        make_spec_visible: true
        proxy_path: sandbox
      - environment: int
        make_spec_visible: true
        depends_on:
            - internal_qa
            - internal_qa_sandbox
      - environment: sandbox
        make_spec_visible: true
        proxy_path: sandbox
        depends_on:
            - internal_qa
            - internal_qa_sandbox
        post_deploy:
            -   template: templates/tests.yml
                parameters:
                    service_name: ${{ variables.service_name }}
                    test_tag: -m sandbox
