name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital

  pipelines:
  - pipeline: build_pipeline
    source: "Reasonable-Adjustments-Build"
    trigger:
      branches:
        exclude:
          - master
          - refs/heads/master
          - refs/tags/v*

pool:
  name: 'AWS-ECS'

variables:
  - template: project.yml

extends:
  template: azure/common/apigee-deployment.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    service_base_path: ${{ variables.service_base_path }}
    short_service_name: ${{ variables.short_service_name }}
    enable_monitoring: false
    apigee_deployments:
      - environment: internal-dev
        post_deploy:
          - template: templates/tests.yml
      - environment: internal-dev-sandbox
        proxy_path: sandbox
