variables:
  service_name: reasonable-adjustment
  service_base_path: reasonable-adjustment-flag
  short_service_name: reasonable-adjustment-flag
  product_display_name: Reasonable Adjustment Flag Api
  product_description: Reasonable Adjustment Flag Api
  spec_file: reasonable-adjustment-flag.json
